#:import hex kivy.utils.get_color_from_hex

<RegisterScreen>:
    name:'register'
    on_enter:
        self.anim_openning_the_screen_img(main_register_pool_zone)
        self.anim_openning_the_screen_text_input(main_register_pool_zone)
        self.anim_openning_the_screen_google_lay(main_register_pool_zone)
        self.anim_openning_the_screen_buttons(main_register_pool_zone)

        
    MainRegisterPool:
        id:main_register_pool_zone

