from kivymd.uix.floatlayout import MDFloatLayout

from elements.profile_anime_list_element.image_of_profile import ImageOfProfile
from elements.profile_anime_list_element.profile_information_element import ProfileInformationElement
from elements.profile_anime_list_element.clickable_lable import ClickableLable
from elements.profile_anime_list_element.list_with_menu_profile_elements import ListWithMenuProfileElements
from elements.profile_anime_list_element.friends_list_on_profile import FriendsListOnProfile


class MainProfilePool(MDFloatLayout):
    pass